MyShoeWorld.UI/Controllers/CartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MyShoeWorld.Dal;
using MyShoeWorld.Models;
using Newtonsoft.Json;


namespace MyShoeWorld.UI.Controllers
{

        public class CartsController : Controller
        {
            private readonly IShoeWorldRepository<Product> _shoeWorldRepository;

            public CartsController(IShoeWorldRepository<Product> shoeWorldRepository)
            {
                this._shoeWorldRepository = shoeWorldRepository;
            }

            public IActionResult MyCart(int productId)
            {
                List<CartDetails> allCartProducts;
                HttpContext.Session.SetInt32("CustomerId", 1);
                if (HttpContext.Session.Get<Cart>("Cart") == null)
                {
                    var cart = new Cart()
                    {
                        CustomerId = Convert.ToInt32(HttpContext.Session.GetInt32("CustomerId")),
                        CartDate = DateTime.Now
                    };
                    HttpContext.Session.Set<Cart>("Cart", cart);
                }
                if (HttpContext.Session.Get<List<CartDetails>>("CartDetails") == null)
                {
                    allCartProducts = new List<CartDetails>();
                    CartDetails details = new CartDetails()
                    {
                        ProductId = productId,
                        Quantity = 1,
                        Size = 7,
                    };
                    allCartProducts.Add(details);
                    HttpContext.Session.Set<List<CartDetails>>("CartDetails", allCartProducts);
                }
                else
                {
                    //var obj = HttpContext.Session.Get<List<CartDetails>>("CartDetails");
                    allCartProducts = HttpContext.Session.Get<List<CartDetails>>("CartDetails");
                    CartDetails details = new CartDetails()
                    {
                        ProductId = productId,
                        Quantity = 1,
                        Size = 7,
                    };
                    allCartProducts.Add(details);
                    HttpContext.Session.Set<List<CartDetails>>("CartDetails", allCartProducts);
                }
                allCartProducts = HttpContext.Session.Get<List<CartDetails>>("CartDetails");
                var cartProducts = from cart in allCartProducts
                                   join
                                   storeproducts in _shoeWorldRepository.GetAll()
                                   on cart.ProductId equals storeproducts.ProductId
                                   select storeproducts;
                return View(cartProducts);

            }
        }
    }

MyShoeWorld.UI/Controllers/ProductsController.cs
using MyShoeWorld.Dal;
using MyShoeWorld.Models;
using Microsoft.AspNetCore.Mvc;

namespace MyShoeWorld.UI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IShoeWorldRepository<Product> _repository;

        public ProductsController(IShoeWorldRepository<Product> repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("A", "A");
            Console.WriteLine(HttpContext.Session.Id);
            var products = _repository.GetAll();
            return View(products);
        }
        //parameterized Route
        public IActionResult CategoryProducts(int id)
        {

            var products=_repository.GetAll().Where(p=>p.CategoryId==id);
            return View("Index",products);
        }
       public IActionResult Details(int id) 
        {
            var products = from product in _repository.GetAll()
                           where product.ProductId == id
                           select product;
            return View(products);
        }
        public IActionResult New(Product  products)
        {
            if (ModelState.IsValid)
            {
                _repository.insert(products);
                int result = _repository.SaveChanges();
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }

            }
            return View();
        }
    }
}

MyShoeWorld.UI/Views/Products/Details.cshtml
@using MyShoeWorld.Models

@model IEnumerable<Product>

@foreach (Product product in Model)
{
    <div class="container">
        <div class="row d-flex justify-content-center ">
            <div class="col-md-8">
                <div class="card bg-body shadow-lg p-3 mb-5 rounded">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="images p-3">
                                <div class="text-center p-4  rounded">
                                    <img id="main-image" src="@product.Picture" class="shadow-lg rounded" width="350" height="300" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="product p-4">
                                <div class="mt-2 mb-3">

                                    <h3 class="text-uppercase">@product.ProductName</h3>
                                    <div class="price d-flex flex-row align-items-center">
                                        <span class="act-price" style="padding-right:20px;"><del>&#8377; @product.UnitPrice</del></span>
                                        <div class="pl-5">
                                            <small class="dis-price ml-2" style="font-size:26px; font-weight:bold;">&#8377; @(product.UnitPrice * (100 - @product.Discount) / 100) </small>

                                            <span class="badge" style="background-color:red; margin-left:5px;">@product.Discount % OFF</span>
                                        </div>
                                    </div>
                                </div>
                                <h6>Warrenty Period : @product.WarrantyPeriod</h6>
                                <h6 class="about">@product.Description</h6>
                                <h6>Made in @product.MadeIn and specially for @product.Gender</h6>
                                <h6>No question ask return policy under @product.ReturnPolicy</h6>
                                <br />

                                <h6 class="text-uppercase fw-bold">Description : </h6>
                                <hr style="width:50%" />
                                <h6>@product.Description</h6>


                                <div class="cart mt-4 align-items-center"> <button class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</button> &nbsp; <i class="fa fa-heart text-muted"></i> &nbsp; <i class="fa fa-share-alt text-muted"></i> </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



}

MyShoeWorld.UI/Views/Products/Index.cshtml
@using MyShoeWorld.Models

@model IEnumerable<Product>

<h1>Welcome to MyshoeWorld Product List </h1>

@*<div class="row row-cols-1 row-cols-md-4 g-4">
    @foreach (Product product in Model)
    {
        <div class="col">
            <div class="card h-100 p-3">
                <div class="card-body">
                    <h4 class="text-center fw-bolder">@product.ProductName</h4>
                </div>
                <img src="~/image/HomeCard1.jpg" height="240" width="320"
                 alt="Skyscrapers" />
                <div class="card-body text-center">
                    <h3 class="card-text">
                        Flat 50% off !!
                    </h3>
                </div>
                <a href="#" class="btn btn-dark">View Details</a>
            <a href="#" class="btn btn-dark">Add To Cart</a>
            </div>
        </div>
    }
</div>*@

<div class="container">
    <div class="row">
        @foreach (Product product in Model)
        {
                <div class="col-sm-3">
                    <div class="card shadow-lg m-5 bg-body-tertiary rounded" style="width: 19rem;">
                        <img src="@product.Picture" class="card-img-top" alt="@product.ProductName" height="240" width="320">
                        <div class="card-body">
                            <h5 class="card-title">@product.ProductName</h5>
                            <p class="card-text">@product.Description</p>
                            <hr>
                            <a asp-action="Details" asp-route-id="@product.ProductId" class="btn btn-dark">View Details</a>
                            <a asp-controller="Carts" asp-action="MyCart" asp-route-productId="@product.ProductId" class="btn btn-dark">Add To Cart</a>
                                
                               @*<a href="#" class="btn btn-dark align-items-center">Add To Cart</a>*@
                            </div>
                        </div>
                    </div>
                
        }
    </div>
</div>

MyShoeWorld.UI/Views/Products/New.cshtml
@model MyShoeWorld.Models.Product

@{
    ViewData["Title"] = "New";
}

<h1>New</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="New">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}