MyShoeWorld.UI/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using MyShoeWorld.Dal;
using MyShoeWorld.Models;

namespace MyShoeWorld.UI.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IShoeWorldRepository<Category> _repository;

        public CategoriesController(IShoeWorldRepository<Category> repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
           
            var categories = _repository.GetAll();
            return View(categories);
        }
        // by default get http
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        //[HttpPut]
        public IActionResult New(Category category)
        {
            if(ModelState.IsValid)
            {
                _repository.insert(category);
                int result = _repository.SaveChanges();
                if(result>0)
                {
                    return RedirectToAction("Index");
                }
                
            }
            return View();
        }
    }
}

MyShoeWorld.UI/Controllers/ProductsController.cs
using MyShoeWorld.Dal;
using MyShoeWorld.Models;
using Microsoft.AspNetCore.Mvc;

namespace MyShoeWorld.UI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IShoeWorldRepository<Product> _repository;

        public ProductsController(IShoeWorldRepository<Product> repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("A", "A");
            Console.WriteLine(HttpContext.Session.Id);
            var products = _repository.GetAll();
            return View(products);
        }
        //parameterized Route
        public IActionResult CategoryProducts(int id)
        {

            var products=_repository.GetAll().Where(p=>p.CategoryId==id);
            return View("Index",products);
        }
       public IActionResult Details(int id) 
        {
            var products = from product in _repository.GetAll()
                           where product.ProductId == id
                           select product;
            return View(products);
        }
        public IActionResult New(Product  products)
        {
            if (ModelState.IsValid)
            {
                _repository.insert(products);
                int result = _repository.SaveChanges();
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }

            }
            return View();
        }
    }
}

MyShoeWorld.UI/Controllers/SecurityController.cs
using Auth0.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Facebook;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MyShoeWorld.UI.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public async Task GoogleLogin()
        {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties()
            {
                RedirectUri = Url.Action("GoogleResponse")
            });
        }
        public async Task<IActionResult> GoogleResponse()
        {
            var result = await HttpContext.AuthenticateAsync(GoogleDefaults.AuthenticationScheme);
            var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim =>
            new
            {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            });
            Console.WriteLine(User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value);
            HttpContext.Session.SetString("Admin", User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value);
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task FacebookLogin()
        {
            Console.WriteLine(User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value);

            var authenticationProperties = new LoginAuthenticationPropertiesBuilder()
                .WithRedirectUri("/")
                .Build();
            await HttpContext.ChallengeAsync(FacebookDefaults.AuthenticationScheme, authenticationProperties);
        }
        public async Task<IActionResult> FacebookLogout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task Auth0Login(string returnUrl = "/")
        {
            var authenticationProperties = new LoginAuthenticationPropertiesBuilder()
                .WithRedirectUri(returnUrl)
                .Build();

            await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
        }

        [Authorize]
        public async Task Auth0Logout()
        {
            var authenticationProperties = new LogoutAuthenticationPropertiesBuilder()
                .WithRedirectUri(Url.Action("Index", "Home"))
                .Build();

            await HttpContext.SignOutAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
}

MyShoeWorld.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyShoeWorld.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    @*<link rel="stylesheet" href="~/MyShoeWorld.UI.styles.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home">
                    <img src="~/Images/Logo.jpg" height="50" width="80"
                         alt="Brand" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated == false)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Security" asp-action="Login">Sign In</a>
                            </li>
                        }
                        @if (Context.User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Security" asp-action="Logout">Sign Out</a>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Products">Products</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" href="#">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sign In</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link" href="#">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Privacy</a>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated == true && Context.Session.GetString("Admin") !=
                        "topaleninad01@gmail.com")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Section</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Categories" asp-action="New">Add New Category</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Products" asp-action="New">Add New Product</a>
                                </div>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <img src="~/Images/Cart.gif" height="50" class="d-block w-100" alt="Cart">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - MyShoeWorld Sponsored By - Bajaj Ltd. - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>